---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install python 36
      package:
        name: python36
        state: latest
      become: yes
    - name: install git
      package:
        name: git
        state: latest
      become: yes
    - name: copy files to other place
      copy:
        src: ./dot_files
        dest: /home/vagrant
      tags:
        - copy

        
  roles:
    - vim
    - tmux
